version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  mongo:
    image: 'mongo:latest'
    restart: always
  #truffle:
      #build:
      #  dockerfile: Dockerfile.dev
      #  context: ./blockchain
      #ports:
      #  - '9545:9545'
      #volumes:
      #  - /app/node_modules
      #  - ./blockchain:/app
  api:
    depends_on:
      - postgres
      - redis
      - mongo
    #build:
      #dockerfile: Dockerfile.dev
    image: chess
    ports: 
      - '3000:3000'
    volumes:
      - /app/node_modules
      - /app/blockchain/node_modules
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - MONGO_URI=mongodb://mongo:27017/chessdb
      - ETH_URI=http://docker.host.internal:9545/
      - NODE_ENV=development
    #  - ETH_URI=http://truffle:9545/